In [1]:
import numpy as np
np.arange(1, 20, 2, dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [5]:
import numpy as np
np.linspace(3.5, 10, 3, dtype = np.int32)

array([ 3,  6, 10])

In [9]:
import numpy as np
np.empty([4, 3],
         dtype = np.int32,
         order = "f")

array([[4128860, 6619251, 6029426],
       [6029375, 7536754, 7340097],
       [3801155, 7667804, 4456560],
       [5570652, 6619251, 7602273]])

In [7]:
import numpy as np
np.ones([4, 3],
         dtype = np.int32,
         order = "f")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])