In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [29]:
#0-D ARRAY
import numpy as np
arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


In [31]:
#1-D ARRAY
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [33]:
#2-D ARRAY
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 5]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 5]]
2


In [35]:
#3-D ARRAY
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [37]:
#ARRAY INDEXING
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [39]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [51]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f"2nd element on 1st row is {arr[0, 1]}" )

2nd element on 1st row is 2


In [57]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f"5th element on 2nd row is: {arr[1, 4]}")

5th element on 2nd row is: 10


In [59]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2]) #THIRD ELEMENT OF THE SECOND ARRAY

6


In [3]:
import numpy as np
arr =np.array(["a", "b", "c", "d", "e", "f", "g"])
print(arr[1:5])

['b' 'c' 'd' 'e']


In [7]:
import numpy as np
arr = np.array(["a", "b", "c", "d", "e", "f"])
print(arr[4:])

['e' 'f']


In [11]:
import numpy as np
arr = np.array(["a", "b", "c", "d", "e", "f"])
print(arr[-3:-1])

['d' 'e']


In [13]:
import numpy as np
arr = np.array(["a", "b", "c", "d", "e", "f"])
print(arr[1:5:2])

['b' 'd']


In [17]:
import numpy as np
arr = np.array(["a", "b", "c", "d", "e", "f"])
print(arr[::2])

['a' 'c' 'e']


In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [25]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [27]:
import numpy as np
arr = np.array(["apple", "banana","cherry"])
print(arr.dtype)

<U6


In [29]:
import  numpy as np
arr = np.array([1, 2, 3, 4], dtype= "S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [31]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [33]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [35]:
type(arr)

numpy.ndarray

In [37]:
import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool
