In [33]:
from numpy import random
x = random.randint(10)
print(x)

7


In [131]:
from numpy import random
x = random.rand()
print(x)

0.8683963516316112


In [85]:
from numpy import random
x = random.randint(100, size=(5))
print(x, type(x))

[75 70 46 47 30] <class 'numpy.ndarray'>


In [101]:
from numpy import random
x = random.randint(100,  size=(3, 5))
print(x)

[[72 85 13 81 89]
 [94  6 82 23 78]
 [88 24 27 86 33]]


In [119]:
from numpy import random
x = random.rand(5)
print(x)

[0.47634523 0.2177966  0.0936617  0.30599107 0.27795467]
